name: sync a fork
on: [push]

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: sync fork
              uses: sudo-bot/action-fork-sync@v1.0.1
              with:
                  source-url: "https://github.com/williamdes/phpmyadmintest.git"
                  fork-url: "https://github.com/williamdes/phpmyadmintest.git"
                  dry-run: "true"
                  clone-depth: "100"
                  branches: STABLE
